<?php

return [
    [
        'id' => 'roti-tawar-putih',
        'name' => 'Roti Tawar Putih',
        'price' => 18000,
        'priceLabel' => 'Rp 18.000',
        'image' => 'images/menu/roti-tawar-putih.jpg',
        'description' => 'Roti tawar putih tanpa kulit, 500gr.',
        'detail' => 'Roti tawar putih lembut tanpa kulit dengan ukuran 500gr. Cocok untuk sarapan, sandwich, atau bekal keluarga.',
        'category' => 'Roti Tawar',
        'serving' => '500gr',
    ],
    [
        'id' => 'roti-tawar-gandum',
        'name' => 'Roti Tawar Gandum',
        'price' => 22000,
        'priceLabel' => 'Rp 22.000',
        'image' => 'images/menu/roti-tawar-gandum.jpg',
        'description' => 'Roti tawar gandum utuh, tinggi serat.',
        'detail' => 'Roti tawar gandum utuh dengan tekstur lembut dan rasa lebih nutty. Pilihan pas untuk menu sarapan tinggi serat.',
        'category' => 'Roti Tawar',
        'serving' => '1 loaf',
    ],
    [
        'id' => 'roti-coklat',
        'name' => 'Roti Coklat',
        'price' => 8000,
        'priceLabel' => 'Rp 8.000',
        'image' => 'images/menu/roti-coklat.jpg',
        'description' => 'Roti manis isian coklat melt.',
        'detail' => 'Roti manis lembut dengan isian coklat yang lumer. Cocok untuk camilan pagi atau sore.',
        'category' => 'Roti Manis',
        'serving' => '1 pcs',
    ],
    [
        'id' => 'roti-keju',
        'name' => 'Roti Keju',
        'price' => 8500,
        'priceLabel' => 'Rp 8.500',
        'image' => 'images/menu/roti-keju.jpg',
        'description' => 'Roti manis isian keju cheddar.',
        'detail' => 'Roti manis dengan isian keju cheddar gurih. Rasanya seimbang antara lembut, manis, dan asin.',
        'category' => 'Roti Manis',
        'serving' => '1 pcs',
    ],
    [
        'id' => 'nastar',
        'name' => 'Nastar',
        'price' => 45000,
        'priceLabel' => 'Rp 45.000',
        'image' => 'images/menu/nastar.jpg',
        'description' => 'Kue nastar isian nanas, 250gr.',
        'detail' => 'Nastar lembut dengan isian nanas manis segar. Dikemas 250gr, cocok untuk suguhan atau hadiah.',
        'category' => 'Kue Kering',
        'serving' => '250gr',
    ],
    [
        'id' => 'kastengel',
        'name' => 'Kastengel',
        'price' => 50000,
        'priceLabel' => 'Rp 50.000',
        'image' => 'images/menu/kastangel.jpg',
        'description' => 'Kue keju gurih, 250gr.',
        'detail' => 'Kastengel gurih dengan aroma keju yang kuat. Dikemas 250gr dan pas untuk hampers atau camilan keluarga.',
        'category' => 'Kue Kering',
        'serving' => '250gr',
    ],
    [
        'id' => 'croissant',
        'name' => 'Croissant',
        'price' => 12000,
        'priceLabel' => 'Rp 12.000',
        'image' => 'images/menu/croissant_.jpg',
        'description' => 'Croissant mentega, crispy.',
        'detail' => 'Croissant mentega dengan lapisan renyah di luar dan lembut di dalam. Cocok untuk teman kopi.',
        'category' => 'Pastry',
        'serving' => '1 pcs',
    ],
    [
        'id' => 'brownies-kukus',
        'name' => 'Brownies Kukus',
        'price' => 35000,
        'priceLabel' => 'Rp 35.000',
        'image' => 'images/menu/brownies.jpg',
        'description' => 'Brownies coklat kukus, loyang 20x20.',
        'detail' => 'Brownies coklat kukus dengan tekstur moist. Ukuran loyang 20x20, cocok untuk keluarga atau acara kecil.',
        'category' => 'Cake',
        'serving' => '20x20',
    ],
    [
        'id' => 'lapis-legit',
        'name' => 'Lapis Legit',
        'price' => 120000,
        'priceLabel' => 'Rp 120.000',
        'image' => 'images/menu/lapis-legit.jpg',
        'description' => 'Kue lapis legit tradisional.',
        'detail' => 'Kue lapis legit tradisional dengan aroma rempah dan tekstur padat lembut. Cocok untuk hadiah dan momen spesial.',
        'category' => 'Cake',
        'serving' => '1 loyang',
    ],
];
